Repository I-Futsal-U/I-Futsal-U-BE, pull requests merged in 2023-06, with the labels that each got.

#1 Mock Data 반환 Controller 생성
  build.gradle
  src/main/java/com/ifutsalu/controller/MatchController.java
  src/main/java/com/ifutsalu/controller/PaymentController.java
  src/main/java/com/ifutsalu/controller/StadiumController.java
  src/main/java/com/ifutsalu/controller/UserController.java
  src/main/java/com/ifutsalu/domain/Match.java
  src/main/java/com/ifutsalu/domain/Payment.java
  src/main/java/com/ifutsalu/domain/Stadium.java
  src/main/java/com/ifutsalu/domain/User.java
  src/main/java/com/ifutsalu/dto/payment/PaymentChargeDto.java
  src/main/java/com/ifutsalu/dto/user/UserJoinDto.java
  src/main/java/com/ifutsalu/dto/user/UserLoginDto.java
  src/main/java/com/ifutsalu/dto/user/UserUpdateDto.java
Labels: mock

#2 Develop infrastructure : AWS Parameter Store 적용
  build.gradle
  src/main/java/com/ifutsalu/IfutsaluApplication.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application-prd.yml
  src/main/resources/application-test.yml
  src/main/resources/application.properties
  src/main/resources/application.yml
  src/test/java/com/ifutsalu/IfutsaluApplicationTests.java
Labels: new_feature

#5 Develop infrastructure : ECR 이미지 업로드 및 CI-prebuild.yml 추가
  .github/workflows/CI-prebuild.yml
  Dockerfile
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: infra
